### ISSUE TITLE
Where is arrow-integrations-jackson-module published?

### ISSUE THREAD

**Issue by KushalP** [arrow-kt/arrow-integrations#18]
Hello! I'd really like to use `OptionModule` that is within arrow-integrations-jackson-module. How can I use this module? Is it published anywhere?

**Comment by rachelcarmena** [comment]
Hi! That module is only available in OSS so far: https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-integration-jackson-module/

So the module is:

```
"io.arrow-kt:arrow-integration-jackson-module:<SNAPSHOT-VERSION>"
```

and it would be necessary to add OSS repository:

```
maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local/" }
```

An inconsistency problem exists with that module: https://github.com/arrow-kt/arrow-incubator/issues/58

**Comment by rachelcarmena** [comment]
Hi @KushalP , #19 has been solved and the module is available in https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-integrations-jackson-module/ now so the dependency would be:

```
"io.arrow-kt:arrow-integrations-jackson-module:<SNAPSHOT-VERSION>"
```

Thanks for your interest!!
