### ISSUE TITLE
["Request"] Add Retrofit integration for IO / Tagless-final

### ISSUE THREAD

**Issue by Hiosdra** [arrow-kt/arrow-integrations#27]
What version are you currently using? 0.11.0-SNAPSHOT
What would you like to see?

Hi, like said in Slack [(link)](https://kotlinlang.slack.com/archives/C8UK6RTHU/p1588153408020000?thread_ts=1587819998.016800&cid=C8UK6RTHU), I wish to see Arrow IO integration for Retrofit. 
I have written that and would very appreciate early feedback: https://github.com/arrow-kt/arrow-integrations/commit/12f2836ccd2fa3357844ad98ae4d03a88c923f52

TODO: 
1. Write more tests ✅
2. Try to make work for `IO<Throwable, Response<T>>`. 
3. Try to generalize for `Kind2<F, Throwable, T>` or even `Kind<F, T>` if possible. ✅

Current usage I've tested on:
```kotlin
interface RecognitionClient {

  @Multipart
  @POST("/calculate")
  fun calculate(@Part file: MultipartBody.Part): IO<Throwable, FaceVectorsDto>

  @POST("/compare")
  fun compare(@Body body: FaceCompareDto): IO<Throwable, FaceCompareResultDto>
}
```
And work fabulous 😃

**Comment by pakoito** [comment]
Does this work for you? https://github.com/arrow-kt/arrow-integrations/tree/master/arrow-integrations-retrofit-adapter :D

**Comment by pakoito** [comment]
Ooooooh for IO directly!

**Comment by Hiosdra** [comment]
> Does this work for you? https://github.com/arrow-kt/arrow-integrations/tree/master/arrow-integrations-retrofit-adapter :D

Yes, I have project for my presentation and it works well ;) 

> Ooooooh for IO directly! 👌

Here you are 😆 tagless-final too 😝 https://github.com/arrow-kt/arrow-integrations/pull/28

**Comment by leandroBorgesFerreira** [comment]
Nice idea. I'll take a look at the PR this Friday. Maybe I have some ideas suggestions =]

**Comment by myuwono** [comment]
higher kind and IO types have been superseded by suspend in arrow 1.x
