### ISSUE TITLE
Java reserved keyword used in Kotlin functions.

### ISSUE THREAD

**Issue by xiamubobby** [arrow-kt/arrow-integrations#30]
Hi Team,

As a member of a not so fashion team. I am facing pushing backs on spreading Kotlin for good. We still heavily rely on vanilla Java currently. Thus interoperability is all we pay attention to, because it is so much beauty even just with the monads from ArrowKT.

Say we use retrofit2, as well as your integration for that. The call adapter class: CallK is having a method called _catch_ which is just what we are in need of.

And due to _catch_ is reserved by Java itself as a keyword. We were having no choice but to use ugly wrapping functions, again.

Shall we please add an alias to that very specific method? You may keep the current one without deletion. It is good naming, and it works under Kotlin anyway. Not Java, unfortunately. How about we just simply do something like:
`val raise = catch`
And I believe it will work like a charm.

Many thanks in advance.

**Comment by myuwono** [comment]
this issue has been inactive for a while. closing this issue
