### ISSUE TITLE
0.11.0 Release of arrow-integrations missing on maven?

### ISSUE THREAD

**Issue by jamesbarry93** [arrow-kt/arrow-integrations#43]
Hey team!

We use io.arrow-kt:arrow-integrations-jackson-module as well as core and syntax. We utilise [renovate](https://github.com/renovatebot/renovate) to keep all our dependencies up to date and our latest run to update to arrow 0.11.0 broke due to arrow-integrations-jackson-module 0.11.0 not being released on maven.

Was the push of 0.11.0 to maven missed? Or should we not rely on the arrow-integrations matching the same version number as core?

Thanks!

**Comment by rachelcarmena** [comment]
Hi @jamesbarry93 :wave: 

It has been removed temporarily until it's updated to work with the rest of libraries.

Please, how does renovate work? Does it just consider core, syntax and that module? How could we help you from our side? 

Thanks in advance!

**Comment by jamesbarry93** [comment]
Hey @rachelcarmena - thanks for coming back to me so quickly.

Without knowing the detail within renovate myself, my understanding from its behaviour is that it scrapes maven (say maven central) for new versions and raises a PR on your service for the new version.

In my particular case, I have my pom.xml configured to share arrow.version in a property (see below)

`<properties>
        <arrow.version>0.10.5</arrow.version>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>io.arrow-kt</groupId>
            <artifactId>arrow-core</artifactId>
            <version>${arrow.version}</version>
        </dependency>
        <dependency>
            <groupId>io.arrow-kt</groupId>
            <artifactId>arrow-syntax</artifactId>
            <version>${arrow.version}</version>
        </dependency>
        <dependency>
            <groupId>io.arrow-kt</groupId>
            <artifactId>arrow-integrations-jackson-module</artifactId>
            <version>${arrow.version}</version>
        </dependency>
    </dependencies>`

This is set up this way assuming that each of the individual artifacts share the same version. Renovate is clever enough to recognise this property, and my assumption is that it is updating the property when it sees that 'arrow-core' or 'arrow-syntax' has a new version. This then causes the build on the PR to fail as it can't find 'arrow-integrations-jackson-module' as it does not exist at that new version value.

So what options do we have:
1. We can break the assumption that arrow-integrations will follow the same versioning as the core stuff, and introduce a new property with its own version - I'm not sure this is the greatest solution as I'm sure others will probably make this assumption - releasing a bom or something like that from your side would probably be required to make it easier for people to take arrows dependencies 'in bulk', similar to how Spring do it. 
2. We release 0.11.0 of 'arrow-integrations-jackson-module' in a stable state, not sure what that looks like from your side, but it would assume that everything works with the other artefacts/modules. This will get us to the ideal state where there is a release across the board for 0.11.0, and the assumption that they all follow the same version is maintained. Going forward releases would need to be synced between the arrow artefacts to stop the issue occurring again.
3. Do nothing, consumers such as myself stay on 0.10.5 until everything is in sync again. This breaks the assumption that a release across all of the arrow suite is atomic (i.e. happens all at once). This will hold some consumers from upgrading to 0.11.0 until everything is in sync again.

Any other ideas/thoughts?

**Comment by rachelcarmena** [comment]
Thanks for all the details @jamesbarry93 :raised_hands: Arrow already provides a BOM file from 0.11.0: https://arrow-kt.io/docs/quickstart/setup/#bom-file

Please, let me check the reasons why that module was removed temporarily :+1:

**Comment by jamesbarry93** [comment]
Nice! I'll update my DependencyManagement to import the bom - but yeah, looks like it's missing from the bom too. I'll await your investigation

**Comment by rachelcarmena** [comment]
Right, the BOM file just includes the published modules for that version and it's available from `0.11.0`. 

`arrow-integrations-jackson-module` was removed because it doesn't work the deserialization of a list with the last changes on `arrow-core-data`. 

All the modules are published together so that module will appear again when it works with the rest of the libraries. It's an isolated case, sorry for the inconveniences. I created an issue to enable the module again: #44

**Comment by myuwono** [comment]
Thanks @jamesbarry93 I believe we'll publish an artefact for 0.11.0 support when #52 is merged. @rachelcarmena keen to understand how that process works because I believe we'll have to publish support 0.12.x and 0.13.x as well.

**Comment by rachelcarmena** [comment]
Yes, we'll do it thanks to your help, @myuwono . Thank you so much!! :raised_hands:

**Comment by rachelcarmena** [comment]
The missing library is already published in Maven Central:

https://repo1.maven.org/maven2/io/arrow-kt/arrow-integrations-jackson-module/0.11.0/

Thanks @myuwono !! Let's continue next week to support the latest Arrow versions :raised_hands:
