### ISSUE TITLE
["Request"] Enable arrow-integrations-jackson-module

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-integrations#44]
What version are you currently using?

0.11.0

What would you like to see?

Enable `arrow-integrations-jackson-module` again. It was removed because of a failure with `arrow-core-data`.

**Comment by myuwono** [comment]
@rachelcarmena i'll be looking into this.

**Comment by rachelcarmena** [comment]
> @rachelcarmena i'll be looking into this.

Great!! I'm going to update this repository to continue the development (I just updated `arrow-incubator` and `arrow-check` and I missed this one :pray: ). I'll let you know when I finished. On my way!!

**Comment by rachelcarmena** [comment]
> @rachelcarmena i'll be looking into this.

Great!! I'm going to update this repository to continue the development (I just updated `arrow-incubator` and `arrow-check` and I missed this one :pray: ). I'll let you know when I finish. On my way!!

**Comment by rachelcarmena** [comment]
@myuwono configuration is already adapted to continue the development :raised_hands:
