### ISSUE TITLE
Bug report: Calling ObjectMapper().registerArrowModule() causes NonEmptyList deserialization to fail with NullPointerException

### ISSUE THREAD

**Issue by vpeurala** [arrow-kt/arrow-integrations#78]
See the failing minimal test case in Pull Request #77 (https://github.com/arrow-kt/arrow-integrations/pull/77).

**Comment by vpeurala** [comment]
This test fails:

`"After ObjectMapper.registerArrowModule() NonEmptyList deserialization fails with NullPointerException" {
      val mapperWithSettings =
        ObjectMapper()
          .registerArrowModule()

      val original = nonEmptyListOf("foo", "bar")
      val serialized: String = mapperWithSettings.writeValueAsString(original)
      val deserialized: NonEmptyList<*> = mapperWithSettings.readValue(serialized, NonEmptyList::class.java)

      deserialized shouldBe original
    }`

**Comment by myuwono** [comment]
thanks @vpeurala that's a good find 🙌
